### ISSUE TITLE
🐞 -  Release for 4.0.1 and 4.0.2 not published on NPM

### ISSUE THREAD

**Issue by edbzn** [taiga-family/ng-morph#325]
### Description

There are two patches 4.0.1 and 4.0.2 published on GitHub releases but not on NPM. It is intended?

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by sevaru** [comment]
Hi

We encountered issues with versions 4.0.1 and 4.0.2, which prompted their deprecation on npm. The problems addressed in [this pull request](https://github.com/taiga-family/ng-morph/pull/326) should resolve those issues, making version 4.0.3 likely to be stable.

Indeed, versions 4.0.1 and 4.0.2 were broken.

Furthermore, version 4.0.3 should not have a problems with peerDeps on  Angular 17.

Thank you!

**Comment by sevaru** [comment]
Version [4.0.3](https://www.npmjs.com/package/ng-morph/v/4.0.3) should work fine.

I'm closing this issue now. Feel free to reopen it if you encounter any problems.
