### ISSUE TITLE
Peer dependency warning

### ISSUE THREAD

**Issue by edbzn** [taiga-family/ng-morph#38]
# 🐞 Bug report

### Description

I get some warning when installing ng-morph:

```
warning " > ng-morph@2.0.0" has unmet peer dependency "@angular-devkit/core@>=11.0.0".
warning " > ng-morph@2.0.0" has unmet peer dependency "@angular-devkit/schematics@>=11.0.0".
```

### Reproduction

Clone [this repository](https://github.com/rx-angular/rx-angular) and run `yarn`. 

### Expected behavior

No warning when installing deps.

### Versions

- ng-morph@2.0.0

If needed:

- Angular 12

**Comment by IKatsuba** [comment]
@edbzn thank you! I check it out

**Comment by sevaru** [comment]
Hi

I've tried it with current version of rx-angular repo and yarn install does not give me any warning
except for tslib ng-morph@3.0.0" has incorrect peer dependency "tslib@2.5.3".
which should be good with 4.0.3
